---
title: "MS"
author: "Erik Bjurström"
date: "2026-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(notame)
library(FELLA)
library(xml2)
library(lemon)
library(cowplot)
library(readxl)
library(gridExtra)
library(svglite)
library(reshape2)
library(notameViz)
library(notameStats)

library(doParallel)
registerDoParallel(cores=4)
```

```{r}
# Loads the converted data file
COMB <- import_from_excel(file = "./input/comb_data.xlsx", sheet = 1,
                        corner_row = 5, corner_column = 6,
                        split_by = c("Column", "Ion Mode"))
```

```{r}
# Splits the data files into POS and NEG
modes <- fix_object(COMB, split_data = TRUE)
```

```{r}
# Initialize empty list for processed objects
processed <- list()
for (i in seq_along(modes)) {
  name <- names(modes)[i]
  mode <- modes[[i]]
  # Set all zero abundances to NA
  mode <- mark_nas(mode, value = 0)
  # Flag features with low detection rate
  mode <- flag_detection(mode, qc_limit = 0.2, group_limit = 0.2)
  # Visualize data before drift correction

  # Correct drift
  corrected <- correct_drift(mode)
  # Visualize data after drift correction

  # Flag low-quality features
  corrected <- corrected %>% 
    assess_quality() %>% 
    flag_quality()
  # Visualize data after removal of low-quality features

  # Save result of iteration
  processed[[i]] <- corrected
}
```

```{r}
# Merges the datasets and removes any QC entries
merged <- merge_notame_sets(processed)
merged_no_qc <- drop_qcs(merged)
```

```{r}
# Imputes missing values. Make sure to set a seed.
set.seed(2024)
imputed <- impute_rf(merged_no_qc)
base <- imputed
```

```{r}
# Performs linear regression on the log-transformed area values
assay(base, "log") <- log(assay(base))
lm_results <- perform_lm(base, assay.type = "log", 
  formula_char = "Feature ~ Group")
base <- join_rowData(base, lm_results)
```

```{r}
# Writes the results to an excel file
write_to_excel(base, file = paste0("./output/", "lm_results.xlsx"))
```

```{r}
# Loads a file which contains the molecule names and their corresponding KEGG ID
# If the molecule has one that is
keggtrans <- read.table(file = "./input/name2kegg.txt", header = T, sep = "\t", quote ="")
```

```{r}
# Creates a data frame that has the Alignment ID, molecule name, KEGG ID,
# log2Fold change, p-value, and FDR. Using this df, you can perform further
# statistical analysis.
input <- lm_results

refer <- data.frame(Alignment_ID = COMB@elementMetadata@listData$Alignment_ID,
                    Feature_ID = COMB@elementMetadata@listData$Feature_ID,
                    Molecule_names = COMB@elementMetadata@listData$Molecule_Name)
refer$Molecule_names <- gsub('.{3}$', '', refer$Molecule_names)
refer <- merge(refer, data.frame( Molecule_names = keggtrans$Query, KEGG = keggtrans$KEGG)) %>% relocate(Alignment_ID)

tmp <- data.frame(Feature_ID = input[,1], l2fc = log2(input[,9]/input[,2]+1), p = input[,14], FDR = input[,15])
tmp <- merge(refer, tmp)
```


```{r}
# Writes the data frame into a tab-delimited text file.
final_out <- tmp

write.table(final_out, file = "./output/final_results.txt", sep = "\t", row.names = F)
```
